name: Repopulate README
on:
  workflow_dispatch: {}
  push: {}

jobs:
  readme:
    concurrency:
      group: readme
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m pip install tabulate humanize
          grep -irl "tar.gz$" lists | awk -F'/' '{print $NF}' > /tmp/alltars
          python .github/scripts/readme_update.py
          mkdir -p /tmp
          cp README.md /tmp/README.md
          COMMIT=$(git rev-parse --short HEAD)
          sed -i "s#/main/#/$COMMIT/#g" /tmp/README.md

      - name: Update README and push
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 20
          shell: bash
          command: |
            set -xe
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git pull origin main || git reset --hard origin/main
            cp /tmp/README.md README.md
            git add README.md
            git commit -m "Update README"
            git push
